#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <boost/filesystem/path.hpp>
#include <optional.hpp>

#include <chrono>
#include <cstdint>
#include <ctime>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

class Empty;

struct SomeEmbed;

// defines an empty embeddable structure.
struct SomeEmbed {
};

// defines an empty class.
class Empty {
public:
  // identifies the instance.
  std::string id;
};

// defines some object graph.
struct SomeGraph {
  // defines some optional array.
  std::experimental::optional<std::vector<int64_t>> optional_array;

  // defines some optional boolean.
  std::experimental::optional<bool> optional_boolean;

  // defines some optional date.
  std::experimental::optional<struct tm> optional_date;

  // defines some optional datetime.
  std::experimental::optional<struct tm> optional_datetime;

  // defines some optional duration.
  std::experimental::optional<std::chrono::nanoseconds> optional_duration;

  // defines some optional float.
  std::experimental::optional<double> optional_float;

  // defines some optional integer.
  std::experimental::optional<int64_t> optional_integer;

  // defines some optional map.
  std::experimental::optional<std::map<std::string, int64_t>> optional_map;

  // defines an optional path.
  std::experimental::optional<boost::filesystem::path> optional_path;

  // defines an optional string.
  std::experimental::optional<std::string> optional_string;

  // defines an optional time.
  std::experimental::optional<struct tm> optional_time;

  // defines an optional time zone.
  std::experimental::optional<std::string> optional_time_zone;

  // defines an optional reference to an instance.
  std::experimental::optional<Empty*> optional_reference;

  // defines an optional embedded structure.
  std::experimental::optional<SomeEmbed> optional_embed;

  // registers Empty instances.
  std::map<std::string, std::unique_ptr<Empty>> empties;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
