# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_str: str,
            unconstrained_str: str) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_str: defines some string.
        :param unconstrained_str: defines an unconstrained string.

        """
        self.some_str = some_str
        self.unconstrained_str = unconstrained_str


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
