package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// Empty defines an embeddable structure without properties.
type Empty struct {
}

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of embeddable structures.
	MapOfEmbeds map[string]Empty
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
