#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

struct Empty;

// defines an embeddable structure without properties.
struct Empty {
};

// defines some object graph.
struct SomeGraph {
  // tests an array of embeddable strucures.
  std::vector<Empty> array_of_embeds;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
