package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize SomeDatetime
	////

	target["some_datetime"] = instance.SomeDatetime.Format(
		"2006/01/02 15-04-05Z")

	////
	// Serialize FormatlessDatetime
	////

	target["formatless_datetime"] = instance.FormatlessDatetime.Format(
		"2006-01-02T15:04:05Z")

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
