package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// defines some datetime.
	SomeDatetime time.Time

	// defines some formatless datetime.
	FormatlessDatetime time.Time
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
