package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import (
	"fmt"
	"math"
	"strconv"
	"strings"
)

// SomeGraphFromJSONable parses SomeGraph from a JSONable value.
//
// If there are any errors, the state of target is undefined.
//
// SomeGraphFromJSONable requires:
//  * target != nil
//  * errors != nil
//  * errors.Empty()
func SomeGraphFromJSONable(
	value interface{},
	ref string,
	target *SomeGraph,
	errors *Errors) {

	if target == nil {
		panic("unexpected nil target")
	}

	if errors == nil {
		panic("unexpected nil errors")
	}

	if !errors.Empty() {
		panic("unexpected non-empty errors")
	}

	cast, ok := value.(map[string]interface{})
	if !ok {
		errors.Add(
			ref,
			fmt.Sprintf(
				"expected a map[string]interface{}, but got: %T",
				value))
		return
	}

	////
	// Parse ArrayOfIntegers
	////

	value0, ok0 := cast[
		"array_of_integers"]

	if !ok0 {
		errors.Add(
			ref,
			"property is missing: array_of_integers")
	} else {
		cast1, ok1 := value0.([]interface{})
		if !ok1 {
			errors.Add(
				strings.Join(
					[]string{
						ref, "array_of_integers"},
					"/"),
				fmt.Sprintf(
					"expected a []interface{}, but got: %T",
					value0))
		} else {
			target1 := make(
				[]int64,
				len(cast1))
			for i1 := range cast1 {
				fcast2, ok2 := (cast1[i1]).(float64)
				if !ok2 {
					errors.Add(
						strings.Join(
							[]string{
								ref, "array_of_integers", strconv.Itoa(i1)},
							"/"),
						fmt.Sprintf(
							"expected a float64, but got: %T",
							cast1[i1]))
				} else if fcast2 != math.Trunc(fcast2) {
					errors.Add(
						strings.Join(
							[]string{
								ref, "array_of_integers", strconv.Itoa(i1)},
							"/"),
						fmt.Sprintf(
							"expected a whole number, but got: %f",
							fcast2))
				// 9223372036854775808.0 == 2^63 is the first float > MaxInt64.
				// -9223372036854775808.0 == -(2^63) is the last float >= MinInt64.
				} else if fcast2 >= 9223372036854775808.0 ||
					fcast2 < -9223372036854775808.0 {

					errors.Add(
						strings.Join(
							[]string{
								ref, "array_of_integers", strconv.Itoa(i1)},
							"/"),
						fmt.Sprintf(
							"expected the value to fit into int64, but got an overflow: %f",
							fcast2))
				} else {
					target1[i1] = int64(fcast2)
				}

				if errors.Full() {
					break;
				}
			}

			target.ArrayOfIntegers = target1
		}
	}

	if errors.Full() {
		return
	}

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
