package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize ArrayOfMaps
	////

	count0 := len(instance.ArrayOfMaps)
	slice0 := instance.ArrayOfMaps
	target0 := make([]interface{}, count0)
	for i0 := 0; i0 < count0; i0++ {
		target1 := make(map[string]interface{})
		map1 := slice0[i0]
		for k1, v1 := range map1 {
			target1[k1] = v1
		}
		target0[i0] = target1
	}
	target["array_of_maps"] = target0

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
