# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_time: datetime.time,
            formatless_time: datetime.time) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_time: defines some time.
        :param formatless_time: defines some formatless time.

        """
        self.some_time = some_time
        self.formatless_time = formatless_time


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
