#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <cstdint>
#include <map>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests a map of integers.
  std::map<std::string, int64_t> map_of_integers;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
