#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <map>
#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests an array of maps.
  std::vector<std::map<std::string, bool>> array_of_maps;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
