package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "fmt"

// EmptyToJSONable converts the instance to
// a JSONable representation.
//
// EmptyToJSONable requires:
//  * instance != nil
//
// EmptyToJSONable ensures:
//  * target != nil
func EmptyToJSONable(
	instance *Empty) (
	target map[string]interface{}) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})

	return
}

// EmbedWithRefToJSONable converts the instance to
// a JSONable representation.
//
// EmbedWithRefToJSONable requires:
//  * instance != nil
//
// EmbedWithRefToJSONable ensures:
//  * target != nil
func EmbedWithRefToJSONable(
	instance *EmbedWithRef) (
	target map[string]interface{}) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})

	////
	// Serialize ReferenceToEmpty
	////

	target["reference_to_empty"] = instance.ReferenceToEmpty.ID

	return
}

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize SomeEmbed
	////

	target["some_embed"] = EmbedWithRefToJSONable(
		&instance.SomeEmbed)

	////
	// Serialize instance registry of Empty
	////

	if len(instance.Empties) > 0 {
		targetEmpties := make(map[string]interface{})
		for id := range instance.Empties {
			emptyInstance := instance.Empties[id]

			if id != emptyInstance.ID {
				err = fmt.Errorf(
					"expected the instance of Empty to have the ID %s according to the registry, but got: %s",
					id, emptyInstance.ID)
				return
			}

			targetEmpties[id] = EmptyToJSONable(
				emptyInstance)
		}

		target["empties"] = targetEmpties
	}

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
