package address

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "fmt"

// PersonToJSONable converts the instance to
// a JSONable representation.
//
// PersonToJSONable requires:
//  * instance != nil
//
// PersonToJSONable ensures:
//  * target != nil
func PersonToJSONable(
	instance *Person) (
	target map[string]interface{}) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})

	////
	// Serialize FullName
	////

	target["full_name"] = instance.FullName

	////
	// Serialize Birthday
	////

	target["birthday"] = instance.Birthday.Format(
		"2006-01-02")

	////
	// Serialize Address
	////

	target["address"] = AddressToJSONable(
		&instance.Address)

	return
}

// AddressToJSONable converts the instance to
// a JSONable representation.
//
// AddressToJSONable requires:
//  * instance != nil
//
// AddressToJSONable ensures:
//  * target != nil
func AddressToJSONable(
	instance *Address) (
	target map[string]interface{}) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})

	////
	// Serialize Text
	////

	target["text"] = instance.Text

	return
}

// Pipeline converts the instance to a JSONable representation.
//
// Pipeline requires:
//  * instance != nil
//
// Pipeline ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func PipelineToJSONable(
	instance *Pipeline) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize Maintainer
	////

	target["maintainer"] = instance.Maintainer.ID

	////
	// Serialize instance registry of Person
	////

	if len(instance.Persons) > 0 {
		targetPersons := make(map[string]interface{})
		for id := range instance.Persons {
			personInstance := instance.Persons[id]

			if id != personInstance.ID {
				err = fmt.Errorf(
					"expected the instance of Person to have the ID %s according to the registry, but got: %s",
					id, personInstance.ID)
				return
			}

			targetPersons[id] = PersonToJSONable(
				personInstance)
		}

		target["persons"] = targetPersons
	}

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
