#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <map>
#include <memory>
#include <string>

namespace some {
namespace graph {

struct SomeGraph;

class Error;

// tests that there are no name conflicts with parse::Error.
class Error {
public:
  // identifies the instance.
  std::string id;
};

// defines some object graph.
struct SomeGraph {
  // registers Error instances.
  std::map<std::string, std::unique_ptr<Error>> errors;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
