package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import (
	"fmt"
	"time"
)

func ExampleDurationToString_oneYear() {
	d := 365 * 24 * time.Hour
	s := durationToString(d)
	fmt.Println(s)
	// Output: P365D
}

func ExampleDurationToString_negativeYear() {
	d := -365 * 24 * time.Hour
	s := durationToString(d)
	fmt.Println(s)
	// Output: -P365D
}

func ExampleDurationToString_hoursMinutesSeconds() {
	d := time.Hour + 2 * time.Minute + 3 * time.Second
	s := durationToString(d)
	fmt.Println(s)
	// Output: PT1H2M3S
}

func ExampleDurationToString_daysHoursMinutesSeconds() {
	d := 24 * time.Hour + 2 * time.Hour + 3 * time.Minute + 4 * time.Second
	s := durationToString(d)
	fmt.Println(s)
	// Output: P1DT2H3M4S
}

func ExampleDurationToString_secondsNanoseconds() {
	d := 1 * time.Second + time.Nanosecond
	s := durationToString(d)
	fmt.Println(s)
	// Output: PT1.000000001S
}

func ExampleDurationToString_secondsManyNanoseconds() {
	d := 1 * time.Second + 1000 * time.Nanosecond
	s := durationToString(d)
	fmt.Println(s)
	// Output: PT1.000001S
}

func ExampleDurationToString_nanoseconds() {
	d := 1 * time.Nanosecond
	s := durationToString(d)
	fmt.Println(s)
	// Output: PT0.000000001S
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
