package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests an array of durations.
	ArrayOfDurations []time.Duration
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
