# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import pathlib
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_paths: typing.MutableMapping[str, pathlib.Path]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_paths: tests a map of paths.

        """
        self.map_of_paths = map_of_paths


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
