# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_strings: typing.List[str]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_strings: tests an array of strings.

        """
        self.array_of_strings = array_of_strings


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
