# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_arrays: typing.List[typing.List[bool]]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_arrays: tests an array of arrays.

        """
        self.array_of_arrays = array_of_arrays


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
