# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""parses JSONable objects."""


import typing

import some.graph
import some.graph.parse


def some_graph_from(
        value: typing.Any,
        ref: str,
        errors: some.graph.parse.Errors
) -> typing.Optional[some.graph.SomeGraph]:
    """
    parses SomeGraph from a JSONable value.

    :param value: JSONable value
    :param ref: reference to the value (e.g., a reference path)
    :param errors: errors encountered during parsing
    :return: parsed SomeGraph, or None if ``errors``
    """
    if errors.full():
        return None

    if not isinstance(value, dict):
        errors.add(
            ref,
            "Expected a dictionary, but got: {}".format(type(value)))
        return None

    graph = some.graph.parse.placeholder_some_graph()

    ##
    # Parse array_of_arrays
    ##

    value_0 = value.get(
        'array_of_arrays',
        None)

    if value_0 is None:
        errors.add(
            ref,
            'Property is missing: array_of_arrays')
    else:
        if not isinstance(value_0, list):
            errors.add(
                '/'.join((
                    ref, 'array_of_arrays')),
                "Expected a list, but got: {}".format(
                    type(value_0)))
        else:
            target_1 = (
                []
            )  # type: typing.List[typing.List[bool]]
            for i_1, item_1 in enumerate(
                    value_0):
                target_item_1 = (
                    None
                )  # type: typing.Optional[typing.List[bool]]
                if not isinstance(item_1, list):
                    errors.add(
                        '/'.join((
                            ref, 'array_of_arrays', str(i_1))),
                        "Expected a list, but got: {}".format(
                            type(item_1)))
                else:
                    target_2 = (
                        []
                    )  # type: typing.List[bool]
                    for i_2, item_2 in enumerate(
                            item_1):
                        target_item_2 = (
                            None
                        )  # type: typing.Optional[bool]
                        if not isinstance(item_2, bool):
                            errors.add(
                                '/'.join((
                                    ref, 'array_of_arrays', str(i_1), str(i_2))),
                                "Expected a bool, but got: {}".format(
                                    type(item_2)))
                        else:
                            target_item_2 = item_2

                        if target_item_2 is not None:
                            target_2.append(
                                target_item_2)

                        if errors.full():
                            break

                    target_item_1 = target_2

                if target_item_1 is not None:
                    target_1.append(
                        target_item_1)

                if errors.full():
                    break

            graph.array_of_arrays = target_1

    if errors.full():
        return None

    if not errors.empty():
        return None

    return graph
