package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// defines some string.
	SomeStr string

	// defines an unconstrained string.
	UnconstrainedStr string
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
