# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_datetimes: typing.List[datetime.datetime]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_datetimes: tests an array of datetimes.

        """
        self.array_of_datetimes = array_of_datetimes


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
