#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <string>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // defines some time zone.
  std::string some_time_zone;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
