# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""parses JSONable objects."""


import typing

import some.graph
import some.graph.parse


def _empty_from(
        value: typing.Any,
        ref: str,
        target: some.graph.Empty,
        errors: some.graph.parse.Errors
) -> None:
    """
    parses Empty from a JSONable value.

    If ``errors``, the attributes of ``target`` have undefined values.

    :param value: JSONable value
    :param ref:
        reference to the value (e.g., a reference path)
    :param target: parsed ``value`` as Empty
    :param errors: errors encountered during parsing
    :return:

    """
    if not isinstance(value, dict):
        errors.add(
            ref,
            "Expected a dictionary, but got: {}".format(
                type(value)))
        return


def empty_from(
        value: typing.Any,
        ref: str,
        errors: some.graph.parse.Errors
) -> typing.Optional[some.graph.Empty]:
    """
    parses Empty from a JSONable value.

    :param value: JSONable value
    :param id: identifier of the instance
    :param ref:
        reference to the value (e.g., a reference path)
    :param errors: errors encountered during parsing
    :return: parsed instance, or None if ``errors``

    """
    target = some.graph.parse.placeholder_empty()

    _empty_from(
        value=value,
        ref=ref,
        target=target,
        errors=errors)

    if not errors.empty():
       return None

    return target


def some_graph_from(
        value: typing.Any,
        ref: str,
        errors: some.graph.parse.Errors
) -> typing.Optional[some.graph.SomeGraph]:
    """
    parses SomeGraph from a JSONable value.

    :param value: JSONable value
    :param ref: reference to the value (e.g., a reference path)
    :param errors: errors encountered during parsing
    :return: parsed SomeGraph, or None if ``errors``
    """
    if errors.full():
        return None

    if not isinstance(value, dict):
        errors.add(
            ref,
            "Expected a dictionary, but got: {}".format(type(value)))
        return None

    graph = some.graph.parse.placeholder_some_graph()

    ##
    # Parse array_of_embeds
    ##

    value_0 = value.get(
        'array_of_embeds',
        None)

    if value_0 is None:
        errors.add(
            ref,
            'Property is missing: array_of_embeds')
    else:
        if not isinstance(value_0, list):
            errors.add(
                '/'.join((
                    ref, 'array_of_embeds')),
                "Expected a list, but got: {}".format(
                    type(value_0)))
        else:
            target_1 = (
                []
            )  # type: typing.List[some.graph.Empty]
            for i_1, item_1 in enumerate(
                    value_0):
                target_item_1 = (
                    None
                )  # type: typing.Optional[some.graph.Empty]
                target_2 = (
                    some.graph.parse.placeholder_empty()
                )
                _empty_from(
                    item_1,
                    '/'.join((
                        ref, 'array_of_embeds', str(i_1))),
                    target_2,
                    errors)
                target_item_1 = target_2

                if target_item_1 is not None:
                    target_1.append(
                        target_item_1)

                if errors.full():
                    break

            graph.array_of_embeds = target_1

    if errors.full():
        return None

    if not errors.empty():
        return None

    return graph
