# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_time_zone: str) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_time_zone: defines some time zone.

        """
        self.some_time_zone = some_time_zone


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
