# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_time_zones: typing.List[str]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_time_zones: tests an array of time zones.

        """
        self.array_of_time_zones = array_of_time_zones


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
