#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <cstdint>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // defines an integer.
  int64_t some_int = 0;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
