package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of time zones.
	MapOfTimeZones map[string]*time.Location
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
