package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// defines some map.
	SomeMap map[string]int64

	// defines some nested map.
	SomeNestedMap map[string]map[string]int64
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
