# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_booleans: typing.List[bool]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_booleans: tests an array of booleans.

        """
        self.array_of_booleans = array_of_booleans


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
