package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize ArrayOfArrays
	////

	count0 := len(instance.ArrayOfArrays)
	slice0 := instance.ArrayOfArrays
	target0 := make([]interface{}, count0)
	for i0 := 0; i0 < count0; i0++ {
		count1 := len(slice0[i0])
		slice1 := slice0[i0]
		target1 := make([]interface{}, count1)
		for i1 := 0; i1 < count1; i1++ {
			target1[i1] = slice1[i1]
		}
		target0[i0] = target1
	}
	target["array_of_arrays"] = target0

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
