#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <chrono>
#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests an array of durations.
  std::vector<std::chrono::nanoseconds> array_of_durations;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
