#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <boost/filesystem/path.hpp>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // defines some path.
  boost::filesystem::path some_path;

  // defines an unconstrained path.
  boost::filesystem::path unconstrained_path;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
