#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <map>
#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests a map of arrays.
  std::map<std::string, std::vector<bool>> map_of_arrays;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
