#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <ctime>
#include <map>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests a map of datetimes.
  std::map<std::string, struct tm> map_of_datetimes;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
