package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests an array of strings.
	ArrayOfStrings []string
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
