#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <map>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests a map of booleans.
  std::map<std::string, bool> map_of_booleans;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
