#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests an array of floats.
  std::vector<double> array_of_floats;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
