#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <cstdint>
#include <map>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // defines some map.
  std::map<std::string, int64_t> some_map;

  // defines some nested map.
  std::map<std::string, std::map<std::string, int64_t>> some_nested_map;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
