# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class Empty:
    """defines an embeddable structure without properties."""


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_embeds: typing.MutableMapping[str, Empty]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_embeds: tests a map of embeddable structures.

        """
        self.map_of_embeds = map_of_embeds


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
