# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeEmbed:
    """defines an embeddable structure."""

    def __init__(
            self,
            some_property: bool) -> None:
        """
        initializes an instance of SomeEmbed with the given values.

        :param some_property: defines a boolean property.

        """
        self.some_property = some_property


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_embeds: typing.MutableMapping[str, SomeEmbed]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_embeds: tests a map of embeddable structures.

        """
        self.map_of_embeds = map_of_embeds


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
