package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of strings.
	MapOfStrings map[string]string
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
