#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <vector>

namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // tests an array of arrays.
  std::vector<std::vector<bool>> array_of_arrays;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
