package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of booleans.
	MapOfBooleans map[string]bool
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
