# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class WithOptional:
    """defines an embeddable with an optional property."""

    def __init__(
            self,
            some_text: typing.Optional[str] = None) -> None:
        """
        initializes an instance of WithOptional with the given values.

        :param some_text: defines an optional property.

        """
        self.some_text = some_text if some_text is not None else None


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_property: WithOptional) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_property: tests an embeddable with an optional property.

        """
        self.some_property = some_property


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
