# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""parses JSONable objects."""


import typing

import some.graph
import some.graph.parse


def _with_optional_from(
        value: typing.Any,
        ref: str,
        target: some.graph.WithOptional,
        errors: some.graph.parse.Errors
) -> None:
    """
    parses WithOptional from a JSONable value.

    If ``errors``, the attributes of ``target`` have undefined values.

    :param value: JSONable value
    :param ref:
        reference to the value (e.g., a reference path)
    :param target: parsed ``value`` as WithOptional
    :param errors: errors encountered during parsing
    :return:

    """
    if not isinstance(value, dict):
        errors.add(
            ref,
            "Expected a dictionary, but got: {}".format(
                type(value)))
        return

    ##
    # Parse some_text
    ##

    value_0 = value.get(
        'some_text',
        None)

    if value_0 is not None:
        if not isinstance(value_0, str):
            errors.add(
                '/'.join((
                    ref, 'some_text')),
                "Expected a string, but got: {}".format(
                    type(value_0)))
        else:
            target.some_text = value_0
    if errors.full():
        return


def with_optional_from(
        value: typing.Any,
        ref: str,
        errors: some.graph.parse.Errors
) -> typing.Optional[some.graph.WithOptional]:
    """
    parses WithOptional from a JSONable value.

    :param value: JSONable value
    :param id: identifier of the instance
    :param ref:
        reference to the value (e.g., a reference path)
    :param errors: errors encountered during parsing
    :return: parsed instance, or None if ``errors``

    """
    target = some.graph.parse.placeholder_with_optional()

    _with_optional_from(
        value=value,
        ref=ref,
        target=target,
        errors=errors)

    if not errors.empty():
       return None

    return target


def some_graph_from(
        value: typing.Any,
        ref: str,
        errors: some.graph.parse.Errors
) -> typing.Optional[some.graph.SomeGraph]:
    """
    parses SomeGraph from a JSONable value.

    :param value: JSONable value
    :param ref: reference to the value (e.g., a reference path)
    :param errors: errors encountered during parsing
    :return: parsed SomeGraph, or None if ``errors``
    """
    if errors.full():
        return None

    if not isinstance(value, dict):
        errors.add(
            ref,
            "Expected a dictionary, but got: {}".format(type(value)))
        return None

    graph = some.graph.parse.placeholder_some_graph()

    ##
    # Parse some_property
    ##

    value_0 = value.get(
        'some_property',
        None)

    if value_0 is None:
        errors.add(
            ref,
            'Property is missing: some_property')
    else:
        target_1 = (
            some.graph.parse.placeholder_with_optional()
        )
        _with_optional_from(
            value_0,
            '/'.join((
                ref, 'some_property')),
            target_1,
            errors)
        graph.some_property = target_1

    if errors.full():
        return None

    if not errors.empty():
        return None

    return graph
