# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_strings: typing.MutableMapping[str, str]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_strings: tests a map of strings.

        """
        self.map_of_strings = map_of_strings


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
