# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_floats: typing.MutableMapping[str, float]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_floats: tests a map of floats.

        """
        self.map_of_floats = map_of_floats


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
