package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of durations.
	MapOfDurations map[string]time.Duration
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
