# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_dates: typing.MutableMapping[str, datetime.date]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_dates: tests a map of dates.

        """
        self.map_of_dates = map_of_dates


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
