# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_durations: typing.MutableMapping[str, datetime.timedelta]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_durations: tests a map of durations.

        """
        self.map_of_durations = map_of_durations


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
