package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize ArrayOfDatetimes
	////

	count0 := len(instance.ArrayOfDatetimes)
	slice0 := instance.ArrayOfDatetimes
	target0 := make([]interface{}, count0)
	for i0 := 0; i0 < count0; i0++ {
		target0[i0] = slice0[i0].Format(
			"2006-01-02T15:04:05Z")
	}
	target["array_of_datetimes"] = target0

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
