package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests an array of datetimes.
	ArrayOfDatetimes []time.Time
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
