package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// WithOptionalToJSONable converts the instance to
// a JSONable representation.
//
// WithOptionalToJSONable requires:
//  * instance != nil
//
// WithOptionalToJSONable ensures:
//  * target != nil
func WithOptionalToJSONable(
	instance *WithOptional) (
	target map[string]interface{}) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})

	////
	// Serialize SomeText
	////

	if instance.SomeText != nil {
		target["some_text"] = (*instance.SomeText)
	}

	return
}

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize SomeProperty
	////

	target["some_property"] = WithOptionalToJSONable(
		&instance.SomeProperty)

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
