package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph converts the instance to a JSONable representation.
//
// SomeGraph requires:
//  * instance != nil
//
// SomeGraph ensures:
//  * (err == nil && target != nil) || (err != nil && target == nil)
func SomeGraphToJSONable(
	instance *SomeGraph) (
	target map[string]interface{}, err error) {

	if instance == nil {
		panic("unexpected nil instance")
	}

	target = make(map[string]interface{})
	defer func() {
		if err != nil {
			target = nil
		}
	}()
	////
	// Serialize SomeIntGt0Lt100
	////

	target["some_int_gt_0_lt_100"] = instance.SomeIntGt0Lt100

	////
	// Serialize SomeIntGe0Le100
	////

	target["some_int_ge_0_le_100"] = instance.SomeIntGe0Le100

	////
	// Serialize UnconstrainedInt
	////

	target["unconstrained_int"] = instance.UnconstrainedInt

	return
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
