# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_date: datetime.date,
            formatless_date: datetime.date) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_date: defines some date.
        :param formatless_date: defines some formatless date.

        """
        self.some_date = some_date
        self.formatless_date = formatless_date


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
