package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of paths.
	MapOfPaths map[string]string
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
