# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_floats: typing.List[float]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_floats: tests an array of floats.

        """
        self.array_of_floats = array_of_floats


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
