# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_datetimes: typing.MutableMapping[str, datetime.datetime]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_datetimes: tests a map of datetimes.

        """
        self.map_of_datetimes = map_of_datetimes


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
