#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!



namespace some {
namespace graph {

struct SomeGraph;

// defines some object graph.
struct SomeGraph {
  // defines a float.
  double some_float = 0.0;
};

}  // namespace graph
}  // namespace some

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
