package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// WithOptional defines a class with an optional property.
type WithOptional struct {
	// identifies the instance
	ID string

	// defines an optional property.
	SomeText *string
}

// SomeGraph defines some object graph.
type SomeGraph struct {
	// registers instances of WithOptional.
	WithOptionals map[string]*WithOptional
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
