# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            map_of_maps: typing.MutableMapping[str, typing.MutableMapping[str, bool]]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param map_of_maps: tests a map of maps.

        """
        self.map_of_maps = map_of_maps


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
