# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""serializes to JSONable objects."""


import collections
import typing

import some.graph


def serialize_some_graph(
        instance: some.graph.SomeGraph,
        ordered: bool = False
) -> typing.MutableMapping[str, typing.Any]:
    """
    serializes an instance of SomeGraph to a JSONable.

    :param instance: the instance of SomeGraph to be serialized
    :param ordered:
        If set, represents the instance properties as a ``collections.OrderedDict``.
        Otherwise, they are represented as a ``dict``.
    :return: JSONable representation
    """
    if ordered:
        target = (
            collections.OrderedDict()
        )  # type: typing.MutableMapping[str, typing.Any]
    else:
        target = dict()

    ##
    # Serialize map_of_maps
    ##

    if isinstance(instance.map_of_maps, collections.OrderedDict):
        target_0 = (
            collections.OrderedDict()
        )  # type: typing.MutableMapping[str, typing.MutableMapping[str, bool]]
    else:
        target_0 = dict()

    for key_0, value_0 in instance.map_of_maps.items():
        if isinstance(value_0, collections.OrderedDict):
            target_1 = (
                collections.OrderedDict()
            )  # type: typing.MutableMapping[str, bool]
        else:
            target_1 = dict()

        for key_1, value_1 in value_0.items():
            target_1[key_1] = value_1
        target_value_0 = target_1
        target_0[key_0] = target_value_0
    target['map_of_maps'] = target_0

    return target


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
