# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""serializes to JSONable objects."""


import collections
import typing

import some.graph


def serialize_some_graph(
        instance: some.graph.SomeGraph,
        ordered: bool = False
) -> typing.MutableMapping[str, typing.Any]:
    """
    serializes an instance of SomeGraph to a JSONable.

    :param instance: the instance of SomeGraph to be serialized
    :param ordered:
        If set, represents the instance properties as a ``collections.OrderedDict``.
        Otherwise, they are represented as a ``dict``.
    :return: JSONable representation
    """
    if ordered:
        target = (
            collections.OrderedDict()
        )  # type: typing.MutableMapping[str, typing.Any]
    else:
        target = dict()

    ##
    # Serialize some_map
    ##

    if isinstance(instance.some_map, collections.OrderedDict):
        target_0 = (
            collections.OrderedDict()
        )  # type: typing.MutableMapping[str, int]
    else:
        target_0 = dict()

    for key_0, value_0 in instance.some_map.items():
        target_0[key_0] = value_0
    target['some_map'] = target_0

    ##
    # Serialize some_nested_map
    ##

    if isinstance(instance.some_nested_map, collections.OrderedDict):
        target_1 = (
            collections.OrderedDict()
        )  # type: typing.MutableMapping[str, typing.MutableMapping[str, int]]
    else:
        target_1 = dict()

    for key_1, value_1 in instance.some_nested_map.items():
        if isinstance(value_1, collections.OrderedDict):
            target_2 = (
                collections.OrderedDict()
            )  # type: typing.MutableMapping[str, int]
        else:
            target_2 = dict()

        for key_2, value_2 in value_1.items():
            target_2[key_2] = value_2
        target_value_1 = target_2
        target_1[key_1] = target_value_1
    target['some_nested_map'] = target_1

    return target


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
