package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

// SomeGraph defines some object graph.
type SomeGraph struct {
	// tests a map of floats.
	MapOfFloats map[string]float64
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
