package somegraph

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

import "time"

// SomeGraph defines some object graph.
type SomeGraph struct {
	// defines some duration.
	SomeDuration time.Duration
}

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
