# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            array_of_dates: typing.List[datetime.date]) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param array_of_dates: tests an array of dates.

        """
        self.array_of_dates = array_of_dates


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
