// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include "parse.h"

#include <string>
#include <vector>

namespace book {
namespace address {

namespace parse {

Errors::Errors(size_t cap) : cap_(cap) {}

void Errors::reserve(size_t expected_errors) {
  errors_.reserve(expected_errors);
}

void Errors::add(const std::string& ref, const std::string& message) {
  if (errors_.size() < cap_) {
    errors_.emplace_back(Error{ref, message});
  }
}

bool Errors::full() const {
  return errors_.size() == cap_;
}

bool Errors::empty() const {
  return errors_.empty();
}

const std::vector<Error>& Errors::get() const {
  return errors_;
}

}  // namespace parse

}  // namespace address
}  // namespace book

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
