#pragma once

// File automatically generated by mapry. DO NOT EDIT OR APPEND!

#include <ctime>
#include <map>
#include <memory>
#include <string>

namespace book {
namespace address {

struct Pipeline;

class Person;

struct Address;

// defines an address.
struct Address {
  // gives the full address.
  std::string text;
};

// defines a contactable person.
class Person {
public:
  // identifies the instance.
  std::string id;

  // gives the full name (including middle names).
  std::string full_name;

  // indicates the birthday in UTC.
  struct tm birthday = tm{0};

  // notes where the person lives.
  Address address;
};

// defines an address book.
struct Pipeline {
  // indicates the maintainer of the address book.
  Person* maintainer = nullptr;

  // registers Person instances.
  std::map<std::string, std::unique_ptr<Person>> persons;
};

}  // namespace address
}  // namespace book

// File automatically generated by mapry. DO NOT EDIT OR APPEND!
