# File automatically generated by mapry. DO NOT EDIT OR APPEND!


"""defines some object graph."""


import datetime
import typing


class SomeGraph:
    """defines some object graph."""

    def __init__(
            self,
            some_duration: datetime.timedelta) -> None:
        """
        initializes an instance of SomeGraph with the given values.

        :param some_duration: defines some duration.

        """
        self.some_duration = some_duration


# File automatically generated by mapry. DO NOT EDIT OR APPEND!
